### ISSUE TITLE
回调嵌套太多，看吐了

### ISSUE THREAD

**Issue by xielei0502** [zPiggy/assets-bundle#1]

**Comment by zPiggy** [comment]
有回调，但是哪来的嵌套？还很多？
使用 async/await 之后，剩下的回调都是必要的。
请举例说明

**Comment by xielei0502** [comment]
assetdb.js 里面 handle相关

**Comment by zPiggy** [comment]
那个文件就是专门为解决 调用官方API中的异步函数造成嵌套回调的 问题而写的，你完全可以不用关心他的调用逻辑。
但是如果你想多了解一些引擎的API，建议直接看官方文档 https://docs.cocos.com/creator/manual/zh/extension/api/asset-db/asset-db-renderer.html?h=asset 或者 https://docs.cocos.com/creator/manual/zh/extension/api/asset-db/asset-db-main.html?h=asset 又或者 https://docs.cocos.com/creator/manual/zh/extension/api/editor-framework/

**Comment by xielei0502** [comment]
嗯嗯，感谢~
